"use client";
import{useCallback,useMemo,useState}from"react";import{Download,Printer}from"lucide-react";
type Donation={receipt_number:string|null;donor_name_snapshot:string;donor_mobile_snapshot:string;amount_minor:number;payment_method:string;status:string;donation_date:string;created_at:string};
type Expense={title:string;category:string;amount_minor:number;expense_date:string;paid_by:string;cancelled_at:string|null};
type Withdrawal={id:string;purpose:string;amount_minor:number;status:string;payment_method:string|null;created_at:string};
type Transaction={external_id:string;type:string;description:string;income_minor:number;expense_minor:number;status:string;created_at:string};
type Props={donations:Donation[];expenses:Expense[];withdrawals:Withdrawal[];transactions:Transaction[]};type Cell=string|number;type ReportRow=Record<string,Cell>;
const labels={daily:"Daily Collection",monthly:"Monthly Collection",donors:"Donor Report",cash:"Cash Collection",online:"Online Collection",expenses:"Expense Report",withdrawals:"Withdrawal Report",ledger:"Complete Ledger"};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(n/100);const csv=(v:Cell)=>`"${String(v).replaceAll('"','""')}"`;
export function ReportsView({donations,expenses,withdrawals,transactions}:Props){const[type,setType]=useState<keyof typeof labels>("daily"),[from,setFrom]=useState(""),[to,setTo]=useState("");const inRange=useCallback((d:string)=>{const day=d.slice(0,10);return(!from||day>=from)&&(!to||day<=to)},[from,to]);
 const rows=useMemo<ReportRow[]>(()=>{const verified=donations.filter(x=>x.status==="VERIFIED"&&inRange(x.donation_date||x.created_at));if(type==="daily"||type==="monthly"){const groups=new Map<string,{count:number,total:number}>();for(const x of verified){const key=type==="monthly"?(x.donation_date||x.created_at).slice(0,7):(x.donation_date||x.created_at).slice(0,10),g=groups.get(key)??{count:0,total:0};g.count++;g.total+=x.amount_minor;groups.set(key,g)}return[...groups].sort((a,b)=>b[0].localeCompare(a[0])).map(([period,g])=>({Period:period,Donations:g.count,"Collection (₹)":(g.total/100).toFixed(2)}))}if(type==="donors"||type==="cash"||type==="online")return donations.filter(x=>inRange(x.donation_date||x.created_at)&&(type==="donors"||(type==="cash"?x.payment_method==="CASH":x.payment_method!=="CASH"))).map(x=>({Date:(x.donation_date||x.created_at).slice(0,10),Receipt:x.receipt_number??"—",Donor:x.donor_name_snapshot,Mobile:x.donor_mobile_snapshot,"Amount (₹)":(x.amount_minor/100).toFixed(2),Method:x.payment_method,Status:x.status}));if(type==="expenses")return expenses.filter(x=>inRange(x.expense_date)).map(x=>({Date:x.expense_date,Title:x.title,Category:x.category.replaceAll("_"," "),"Paid by":x.paid_by,"Amount (₹)":(x.amount_minor/100).toFixed(2),Status:x.cancelled_at?"CANCELLED":"ACTIVE"}));if(type==="withdrawals")return withdrawals.filter(x=>inRange(x.created_at)).map(x=>({Date:x.created_at.slice(0,10),ID:x.id.slice(0,8).toUpperCase(),Purpose:x.purpose,"Amount (₹)":(x.amount_minor/100).toFixed(2),Method:x.payment_method??"—",Status:x.status}));return transactions.filter(x=>inRange(x.created_at)).map(x=>({Date:x.created_at.slice(0,10),"Transaction ID":x.external_id,Type:x.type,Description:x.description,"Income (₹)":(x.income_minor/100).toFixed(2),"Expense (₹)":(x.expense_minor/100).toFixed(2),Status:x.status}))},[type,donations,expenses,withdrawals,transactions,inRange]);
 const totals=useMemo(()=>({collection:donations.filter(x=>x.status==="VERIFIED"&&inRange(x.donation_date||x.created_at)).reduce((s,x)=>s+x.amount_minor,0),expense:expenses.filter(x=>!x.cancelled_at&&inRange(x.expense_date)).reduce((s,x)=>s+x.amount_minor,0),withdrawal:withdrawals.filter(x=>x.status==="COMPLETED"&&inRange(x.created_at)).reduce((s,x)=>s+x.amount_minor,0)}),[donations,expenses,withdrawals,inRange]);
 function download(){if(!rows.length)return;const heads=Object.keys(rows[0]),body=[heads.map(csv).join(","),...rows.map(r=>heads.map(h=>csv(r[h])).join(","))].join("\r\n"),blob=new Blob(["\ufeff"+body],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`ganpati-${type}-report.csv`;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}const heads=rows[0]?Object.keys(rows[0]):[];
 return <><div className="card mt-7 p-5"><div className="grid gap-4 md:grid-cols-3"><label><span className="label">Report</span><select className="input" value={type} onChange={e=>setType(e.target.value as keyof typeof labels)}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label><span className="label">From date</span><input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span className="label">To date</span><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="mt-5 flex flex-wrap gap-3"><button className="btn btn-primary" onClick={download} disabled={!rows.length}><Download size={18}/>Export CSV</button><button className="btn border" onClick={()=>window.print()}><Printer size={18}/>Print / Save PDF</button></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="card p-5"><p className="text-sm text-stone-500">Verified collection</p><p className="mt-1 text-2xl font-bold">{money(totals.collection)}</p></div><div className="card p-5"><p className="text-sm text-stone-500">Active expenses</p><p className="mt-1 text-2xl font-bold">{money(totals.expense)}</p></div><div className="card p-5"><p className="text-sm text-stone-500">Completed withdrawals</p><p className="mt-1 text-2xl font-bold">{money(totals.withdrawal)}</p></div></div><section className="card mt-6 overflow-hidden"><div className="border-b p-5"><h2 className="text-2xl">{labels[type]}</h2><p className="text-sm text-stone-500">{rows.length} row{rows.length===1?"":"s"}</p></div>{!rows.length?<p className="p-6 text-stone-500">No records found for this report and date range.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-stone-50 text-stone-500"><tr>{heads.map(h=><th className="whitespace-nowrap px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr className="border-t" key={i}>{heads.map(h=><td className="whitespace-nowrap px-4 py-4" key={h}>{r[h]}</td>)}</tr>)}</tbody></table></div>}</section></>}
