"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Row={id:string;purpose:string;amount_minor:number;status:string;payment_method:string|null;created_at:string;cancelled_at:string|null;cancellation_reason:string|null};
const allowed=new Set(["image/jpeg","image/png","image/webp","application/pdf"]);
const money=(minor:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(minor/100);

export function WithdrawalManager({rows}:{rows:Row[]}){
 const router=useRouter();
 const[busy,setBusy]=useState(""),[error,setError]=useState(""),[saved,setSaved]=useState("");
 const[cancelId,setCancelId]=useState(""),[cancelPurpose,setCancelPurpose]=useState(""),[reason,setReason]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget,f=new FormData(form),amount=Number(f.get("amount")),file=f.get("document") as File;if(!Number.isFinite(amount)||amount<1){setError("Enter a valid amount.");return}if(file?.size&&(!allowed.has(file.type)||file.size>5242880)){setError("Document must be PDF, JPG, PNG or WebP up to 5 MB.");return}setBusy("request");setError("");setSaved("");const sb=createClient(),{data:{user}}=await sb.auth.getUser();if(!user){setError("Your session expired. Sign in again.");setBusy("");return}const{data:profile}=await sb.from("users").select("mandal_id").eq("id",user.id).single();if(!profile){setError("Your account is not linked to a Mandal.");setBusy("");return}let path:string|null=null;if(file?.size){path=`${profile.mandal_id}/withdrawals/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-").slice(-100)}`;const{error}=await sb.storage.from("mandal-documents").upload(path,file,{upsert:false,contentType:file.type});if(error){setError("Supporting document could not be uploaded.");setBusy("");return}}const{error}=await sb.rpc("request_withdrawal",{p_amount_minor:Math.round(amount*100),p_purpose:String(f.get("purpose")??""),p_payment_method:String(f.get("payment_method")??"OTHER"),p_description:String(f.get("description")??""),p_document_path:path});if(error){if(path)await sb.storage.from("mandal-documents").remove([path]);setError(error.message||"Withdrawal could not be requested.");setBusy("");return}form.reset();setSaved("Withdrawal requested. It does not reduce the balance until completed.");setBusy("");router.refresh()}
 async function act(id:string,action:string){const warning=action==="COMPLETE"?"Complete this withdrawal now? This will create the ledger expense and reduce the available balance.":`${action[0]+action.slice(1).toLowerCase()} this withdrawal?`;if(!window.confirm(warning))return;setBusy(id+action);setError("");const{error}=await createClient().rpc("transition_withdrawal",{p_withdrawal_id:id,p_action:action});if(error)setError(error.message||"Status could not be changed.");else{setSaved(`Withdrawal ${action.toLowerCase()}d successfully.`);router.refresh()}setBusy("")}
 async function cancel(){if(reason.trim().length<5){setError("Enter a cancellation reason of at least 5 characters.");return}setBusy(cancelId+"CANCEL");setError("");const{error}=await createClient().rpc("cancel_withdrawal_request",{p_withdrawal_id:cancelId,p_reason:reason});if(error){setError(error.code==="42501"?"Only a Super Admin can cancel withdrawal requests.":error.message||"Withdrawal could not be cancelled.");setBusy("");return}setCancelId("");setReason("");setSaved("Withdrawal request cancelled. No balance or ledger entry was changed.");setBusy("");router.refresh()}
 function openCancel(row:Row){setCancelId(row.id);setCancelPurpose(row.purpose);setReason("");setError("")}
 return <>
  <form onSubmit={submit} className="card mt-7 p-5 md:p-7"><div className="grid gap-5 sm:grid-cols-2"><label><span className="label">Amount (₹)</span><input className="input" name="amount" type="number" min="1" max="10000000" step="0.01" required/></label><label><span className="label">Payment method</span><select className="input" name="payment_method"><option>UPI</option><option>NETBANKING</option><option>CARD</option><option>CASH</option><option>OTHER</option></select></label><label className="sm:col-span-2"><span className="label">Purpose</span><input className="input" name="purpose" minLength={3} maxLength={200} required/></label><label className="sm:col-span-2"><span className="label">Description (optional)</span><textarea className="input" name="description" maxLength={2000} rows={3}/></label><label className="sm:col-span-2"><span className="label">Supporting document (optional)</span><input className="input" name="document" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp"/><span className="mt-1 block text-xs text-stone-500">Private file, maximum 5 MB.</span></label></div><button className="btn btn-primary mt-6" disabled={!!busy}>{busy==="request"?<Loader2 className="animate-spin" size={18}/>:null}{busy==="request"?"Requesting…":"Request withdrawal"}</button></form>
  {error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</p>}{saved&&<p className="mt-5 flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800"><CheckCircle2 size={18}/>{saved}</p>}
  <section className="card mt-7 overflow-hidden"><div className="border-b p-5"><h2 className="text-2xl">Withdrawal requests</h2></div>{rows.length===0?<p className="p-6 text-stone-500">No withdrawals requested.</p>:<div className="divide-y">{rows.map(x=>{const displayStatus=x.cancelled_at?"CANCELLED":x.status;return <div className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between" key={x.id}><div><p className={x.cancelled_at?"font-bold text-stone-500 line-through":"font-bold"}>{x.purpose}</p><p className="text-sm text-stone-500">{money(x.amount_minor)} · {x.payment_method??"—"} · {new Date(x.created_at).toLocaleDateString("en-IN")}</p><span className={`mt-2 inline-block rounded-full px-3 py-1 text-xs font-bold ${x.cancelled_at?"bg-red-50 text-red-700":"bg-stone-100"}`}>{displayStatus}</span>{x.cancelled_at&&<p className="mt-2 text-sm text-stone-600"><span className="font-bold">Reason:</span> {x.cancellation_reason??"Not recorded"}</p>}</div><div className="flex flex-wrap gap-2">{x.status==="REQUESTED"&&!x.cancelled_at&&<><button className="btn border text-red-700" disabled={!!busy} onClick={()=>openCancel(x)}>Cancel withdrawal</button><button className="btn btn-primary" disabled={!!busy} onClick={()=>act(x.id,"APPROVE")}>Approve</button></>}{x.status==="APPROVED"&&!x.cancelled_at&&<><button className="btn border text-red-700" disabled={!!busy} onClick={()=>openCancel(x)}>Cancel withdrawal</button><button className="btn btn-primary" disabled={!!busy} onClick={()=>act(x.id,"COMPLETE")}>Complete withdrawal</button></>}</div></div>})}</div>}</section>
  {cancelId&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="card w-full max-w-md p-6"><h2 className="text-2xl">Cancel {cancelPurpose}?</h2><p className="mt-2 text-sm text-stone-600">The request will stay visible as CANCELLED. No ledger or balance entry will be created. Completed withdrawals cannot be cancelled here.</p><label className="mt-5 block"><span className="label">Cancellation reason</span><textarea className="input" value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} rows={3}/></label>{error&&<p className="mt-3 text-sm font-semibold text-red-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button className="btn border" onClick={()=>{setCancelId("");setError("")}} disabled={!!busy}>Keep request</button><button className="btn bg-red-700 text-white" onClick={cancel} disabled={!!busy}>{busy?"Cancelling…":"Confirm cancellation"}</button></div></div></div>}
 </>;
}
